### ISSUE TITLE
Configure Docker for Backend

### ISSUE THREAD

**Issue by anastasrado** [anastasrado/HealthHub#5]
#### Description:

1. Create Dockerfile for Backend:
   - Create a Dockerfile in the backend directory with instructions for building the Docker image.
     ```Dockerfile
     # Use the official Node.js image as a parent image
     FROM node:16

     # Set the working directory
     WORKDIR /usr/src/app

     # Copy package.json and package-lock.json
     COPY package*.json ./

     # Install dependencies
     RUN npm install

     # Copy the rest of the application code
     COPY . .

     # Expose port 3000
     EXPOSE 3000

     # Command to run the application
     CMD ["npm", "run", "start:prod"]
     ```

2. Create Docker Compose File:
   - Create a docker-compose.yml file to define services and configure networking.
     ```yaml
     version: '3'
     services:
       backend:
         build:
           context: ./backend
         ports:
           - "3000:3000"
         environment:
           - NODE_ENV=production
           - DATABASE_URL=your_database_url
     ```

3. Test Docker Setup:
   - Build and run the Docker container for the backend.
     ```bash
     docker-compose up --build
     ```

#### Acceptance Criteria:
- Dockerfile and Docker Compose file are created and functional.
- Backend application runs successfully in a Docker container.

---
